language: node_js
node_js: 
  - 14
before_install:
  - npm install -g codecov
script:
  - npm run docs
  - npm test
  - codecov
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: main
