language: node_js
node_js: 
  - 14
before_install:
  - npm install -g codecov
script:
  - npm docs
  - npm test
  - codecov
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: docs
  on:
    branch: main
